version: '3'
services:
  redis:
    image: redis:6.0.3-alpine
    restart: always
    expose:
      - '6379'

  web:
    build: .
    command: flask run -h 0.0.0.0
    depends_on:
      - "redis"
    env_file:
      - .dockerenv
    ports:
      - "5000:5000"
    volumes:
      - .:/app/

  worker:
    build: .
    command: celery worker -A easyto_api.celery_app:app --loglevel=info
    depends_on:
      - "redis"
    env_file:
      - .dockerenv
    ports:
      - "6379:6379"
    volumes:
      - .:/app/
